### ISSUE TITLE
Visuino + Piduino

### ISSUE THREAD

**Issue by tcpipchip** [epsilonrt/piduino#29]
https://nina-b302-wifi-arduino.blogspot.com/2023/07/raspbery-pi-zero-sendo-programado-em.html
https://nina-b302-wifi-arduino.blogspot.com/2023/07/o-objetivo-deste-blog-e-como-programar.html

**Comment by tcpipchip** [comment]
https://nina-b302-wifi-arduino.blogspot.com/2023/07/o-objetivo-deste-blog-e-como-programar_45.html

**Comment by epsilonrt** [comment]
?
