### ISSUE TITLE
Problem with the compilation (lib)

### ISSUE THREAD

**Issue by Assleiv** [epsilonrt/piduino#4]
When you have to compile in geany for exemple, you have to manually add two libs like this:
sudo apt install libcppdb-dev pkg-config cmake libudev-dev
It is present in the wiki page in build from source page.

**Comment by epsilonrt** [comment]
Hi,
Hep, I had to forget the dependency in the libpiduino-dev package.
I will fix that as soon as possible.
Hasta the vista baby ;-)
