### ISSUE TITLE
std system error

### ISSUE THREAD

**Issue by capriciousduck** [epsilonrt/piduino#5]
When executing pido or pinfo I get the following error

terminate called after throwing an instance of 'std::system_error'
  what():  It seems that this system is not supported !: Operation not supported
Aborted

**Comment by epsilonrt** [comment]
Hi,
This exception indicates that the automatic detection did not find the Pi board model.
Could you tell me the Pi board model you use?

**Comment by capriciousduck** [comment]
I use the Rpi 3 Model B

**Comment by epsilonrt** [comment]
Ok,
can you give me the result of `cat /proc /cpuinfo`?

**Comment by capriciousduck** [comment]
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : 2a02082
Serial          : 000000004192b6ac

**Comment by capriciousduck** [comment]
Thank you very much for your fast reply.

**Comment by epsilonrt** [comment]
There is a problem with revision number 0x2a02082, this number is not registered on the site [RPi Hardware](https://elinux.org/RPi_HardwareHistory#Board_Revision_History). Could you give me the link to the page of the builder of this board ?

**Comment by capriciousduck** [comment]
I dont know of any page of the builder. I purchased the Pi on amazon an year ago.

**Comment by capriciousduck** [comment]
Any I have seen that my board is out of warranty when I installed wiringPi

**Comment by capriciousduck** [comment]
Here is the output of gpio -v command 

gpio version: 2.46
Copyright (c) 2012-2018 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Raspberry Pi Details:
  Type: Pi 3, Revision: 02, Memory: 1024MB, Maker: Sony [Out of Warranty]
  * Device tree is enabled.
  *--> Raspberry Pi 3 Model B Rev 1.2
  * This Raspberry Pi supports user-level GPIO access.

**Comment by epsilonrt** [comment]
How did you install? from the sources?

**Comment by capriciousduck** [comment]
No. From the raspbian repository

**Comment by capriciousduck** [comment]
via apt-get

**Comment by epsilonrt** [comment]
Okay, there is an error in the revision number on the RPi Hardware website (I can not test all the boards versions !!). I would correct in the next version of the database.
For the moment, I propose to modify the file `/etc/piduino.conf`.
Remove the # from the last line to have `revision=0xa02082`

**Comment by capriciousduck** [comment]
Ok

**Comment by capriciousduck** [comment]
Thank you for your help.

**Comment by capriciousduck** [comment]
And I want to control the GPIO via bluetooth using an android app. Should I need to install any other libraries or can it be done via Serial.read()  ?

**Comment by capriciousduck** [comment]
I previously used an app to control arduino via bluetooth serial communication. Can I use the same app to control the Pi serial ?

**Comment by epsilonrt** [comment]
piduino is designed so that the native arduino code works, so no problem to use the Serial object. no need for additional libraries.

**Comment by epsilonrt** [comment]
look at the example [ASCIITable](https://github.com/epsilonrt/piduino/blob/master/examples/communication/ASCIITable/ASCIITable.cpp)

**Comment by capriciousduck** [comment]
Hi, I'm still getting the std error

**Comment by epsilonrt** [comment]
it should be installed in `/usr/share/doc/piduino/example`

**Comment by capriciousduck** [comment]
I've set my revision to  2a02082 without the 0x at the start and executing pinfo, I get that the board is Raspberry Pi B instead of Raspberry Pi 3 B and pido readall showed less than 40 GPIO  pins

**Comment by epsilonrt** [comment]
did you modify the configuration file?

**Comment by capriciousduck** [comment]
Yes. I just did what you said.

**Comment by capriciousduck** [comment]
I remove the # and rebooted the Pi and checked but no success

**Comment by capriciousduck** [comment]
Now I set the revision to 2a02082 and executed pinfo I got the info below


Name            : RaspberryPi B
Family          : RaspberryPi
Database Id     : 0
Manufacturer    : Unknown
Board Revision  : 0x2
SoC             : Bcm2708 (Broadcom)
Memory          : 1024MB
GPIO Id         : 1
PCB Revision    : 1
Serial Ports    : /dev/ttyAMA0




See it is showing as Raspi B instead of RPi 3B

**Comment by capriciousduck** [comment]
pido readall gives me this 


      P1 (#1)
+-----+-----+----------+------+---+----++----+---+------+----------+-----+-----+
| sOc | iNo |   Name   | Mode | V | Ph || Ph | V | Mode |   Name   | iNo | sOc |
+-----+-----+----------+------+---+----++----+---+------+----------+-----+-----+
|     |     |     3.3V |      |   |  1 || 2  |   |      | 5V       |     |     |
|   0 |  30 |     SDA0 | ALT0 | 0 |  3 || 4  |   |      | 5V       |     |     |
|   1 |  31 |     SCL0 | ALT0 | 0 |  5 || 6  |   |      | GND      |     |     |
|   4 |   7 |    GPIO4 | ALT4 | 1 |  7 || 8  | 0 | ALT4 | GPIO14   | 15  | 14  |
|     |     |      GND |      |   |  9 || 10 | 1 | ALT4 | GPIO15   | 16  | 15  |
|  17 |   0 |     RTS1 | ALT5 | 1 | 11 || 12 | 1 | ALT4 | SPI1CE0  | 1   | 18  |
|  21 |  29 |   GPIO21 |   IN | 1 | 13 || 14 |   |      | GND      |     |     |
|  22 |   3 |  ARMTRST | ALT4 | 1 | 15 || 16 | 0 | OUT  | GPIO23   | 4   | 23  |
|     |     |     3.3V |      |   | 17 || 18 | 1 | ALT4 | ARMTDO   | 5   | 24  |
|  10 |  12 | SPI0MOSI | ALT0 | 1 | 19 || 20 |   |      | GND      |     |     |
|   9 |  13 |    GPIO9 | ALT2 | 1 | 21 || 22 | 1 | ALT4 | ARMTCK   | 6   | 25  |
|  11 |  14 | SPI0SCLK | ALT0 | 1 | 23 || 24 | 1 | ALT4 | GPIO8    | 10  | 8   |
|     |     |      GND |      |   | 25 || 26 | 0 | ALT5 | GPIO7    | 11  | 7   |
+-----+-----+----------+------+---+----++----+---+------+----------+-----+-----+
| sOc | iNo |   Name   | Mode | V | Ph || Ph | V | Mode |   Name   | iNo | sOc |
+-----+-----+----------+------+---+----++----+---+------+----------+-----+-----+

**Comment by capriciousduck** [comment]
Only 26 pins instead of 40 GPIO

**Comment by epsilonrt** [comment]
No no ! 0x2a02082 is not in the database ! you have to leave `0xa02082`, that corresponds to your board:
`27|RaspberryPi 3 (0xA02082)|1024|1.2|7|3|1|1|0|0`

**Comment by capriciousduck** [comment]
So what is the revision I should put in the file ? Can you paste it here ?

**Comment by epsilonrt** [comment]
you must have `revision=0xa02082` on the last line

**Comment by capriciousduck** [comment]
Yeah I changed it to the above revision, but still I get the same error

**Comment by capriciousduck** [comment]
here is my piduino.conf file

cat /etc/piduino.conf
# PiDuino configuration file
connection_info="sqlite3:db=/usr/share/piduino/piduino.db"

# Allows you to force the board tag (Armbian)
# !! Be careful, this is at your own risk !!
# !! Forcing an incorrect value may destroy GPIO pins !!
#tag="nanopineocore"

# Allows forcing the revision of the board (Raspbian)
# !! Be careful, this is at your own risk !!
# !! Forcing an incorrect value may destroy GPIO pins !!
revision=0xa02082

**Comment by epsilonrt** [comment]
```
# Allows forcing the revision of the board (Raspbian)
# !! Be careful, this is at your own risk !!
# !! Forcing an incorrect value may destroy GPIO pins !!
revision=0xa02082
```

**Comment by epsilonrt** [comment]
great, that's it

**Comment by capriciousduck** [comment]
But still I get the error. It's not working

**Comment by epsilonrt** [comment]
it works ?

**Comment by capriciousduck** [comment]
no.

**Comment by capriciousduck** [comment]
I still get the std system error

**Comment by epsilonrt** [comment]
argh !

**Comment by capriciousduck** [comment]
what should I do now ?

**Comment by epsilonrt** [comment]
can you send me the file /etc/piduino.conf by mail on epsilonrt@gmail.com?

**Comment by capriciousduck** [comment]
Yop, will send it right now.

**Comment by capriciousduck** [comment]
Check your inbox. I've sent the file

**Comment by epsilonrt** [comment]
I received ! the file is good, it should work ...
I found the page with the correct revision numbers:

https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md

I will update the database and update the package, but it will not be until this afternoon because there I have no raspberry pi available ...

**Comment by capriciousduck** [comment]
You mean you will update the package by the end of day ?

**Comment by epsilonrt** [comment]
Let me know if it works ... I warn you when the package has been updated.

**Comment by capriciousduck** [comment]
Sure !

**Comment by capriciousduck** [comment]
are all arduino commands supported in piduino ?

**Comment by epsilonrt** [comment]
Yes !
that's the purpose of the thing!

**Comment by capriciousduck** [comment]
so if i connect my android app to raspberry pi via bluetooth and with just Serial.read() can i receive data to raspberry pi from my android app ?

**Comment by capriciousduck** [comment]
I would like to discuss about this in detail after the revision issue is fixed.

**Comment by epsilonrt** [comment]
I just analyzed the problem, I'll have to modify the code because your revision number has its F bit to 1. On older version of Raspbian, this bit was hidden. So it will take a little longer ...

**Comment by capriciousduck** [comment]
How many days ?

**Comment by capriciousduck** [comment]
I was very eager to use piduino in my project ? Is there any temporary fix so that I can use Piduino until you update the code ?

**Comment by epsilonrt** [comment]
could you give me the version of raspbian that you use (the date), thanks

**Comment by capriciousduck** [comment]
Yup, the latest one. I just downloaded it today.

**Comment by epsilonrt** [comment]
Ok, I'm currently going with my students ... it's not easy. This will be done in the evening, here it is 16:00 at the latest tomorrow morning.
Normally, manual modification of the piduino.conf file should have solved the problem, so there is a bug. I need to recreate your environment to understand why it does not work. piduino is in the development phase, even if it is already very stable, my students will use it in their project of end of study, it is perhaps your case?
