### ISSUE TITLE
Std error

### ISSUE THREAD

**Issue by capriciousduck** [epsilonrt/piduino#6]
I still get the same error. I've changed the revision but still I get the std system error

**Comment by epsilonrt** [comment]
The raspbian piduino repository has been updated to version 0.3.41, thinking about removing `/etc/piduino.conf` before doing an `apt update` then `apt upgrade`.

**Comment by capriciousduck** [comment]
shall I reinstall piduino instead of upgrading ?

**Comment by capriciousduck** [comment]
Thank You ! It's working now.

**Comment by capriciousduck** [comment]
By, the way connecting to rpi with bluetooth and executing Serial.read() , can I send data ?

**Comment by capriciousduck** [comment]
I mean will the data be transferred via serial or should I setup anything else ?
