### ISSUE TITLE
IDE

### ISSUE THREAD

**Issue by capriciousduck** [epsilonrt/piduino#7]
Can I program the Pi using the arduino IDE ? I mean I want to connect my pi to arduino IDE and program it. Is it possible ??

**Comment by epsilonrt** [comment]
No it is not planned. Piduino does not allow cross development.
Piduino emulates the Arduino API (ie the programming interface).
Did you read the wiki? https://github.com/epsilonrt/piduino/wiki/Examples
I advise you to use Codelite (`sudo apt install codelite*`), on a Raspberry Pi 3 it is very fluid and you can do step by step (there is a project model Piduino).
